columns: 
  - Pregnancies: int
  - Glucose: int
  - BloodPressure: int
  - SkinThickness: int
  - Insulin: int
  - BMI: float
  - DiabetesPedigreeFunction: float
  - Age: int
  - Outcome: int

numerical_columns:
  - Pregnancies
  - BloodPressure
  - SkinThickness
  - DiabetesPedigreeFunction
  - Age
  - Outcome

categorical_columns:
  - BMI
  - Insulin
  - Glucose

drop_columns: 
  - _id

# for data transformation
robust_scaler_columns:
  - Pregnancies
  - BloodPressure
  - SkinThickness
  - DiabetesPedigreeFunction
  - Age
  - BMI
  - Insulin
  - Glucose

standard_scaler_columns:
  - Pregnancies
  - BloodPressure
  - SkinThickness
  - DiabetesPedigreeFunction
  - Age
  - BMI
  - Insulin
  - Glucose


columns_to_replace_zeros:
  - Pregnancies
  - Glucose
  - BloodPressure
  - SkinThickness
  - Insulin
  - BMI
  - DiabetesPedigreeFunction
  - Age

columns_to_apply_one_hot_encoding:
  - NewBMI
  - NewInsulinScore
  - NewGlucose